USE ECOMMERCE
GO
CREATE SCHEMA Bdx
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE TABLE [Bdx].[Utenti] (
	[Id] [int] NOT NULL IDENTITY(1,1),
	[Username] [varchar](255) NOT NULL,
	[Nome] [varchar](255) NOT NULL,
	[Cognome] [varchar](255) NOT NULL
,CONSTRAINT [PK_Utenti] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [Bdx].[Prodotti] (
	[Id] [int] NOT NULL IDENTITY(1,1),
	[Nome] [varchar](255) NOT NULL,
	[Quantita] [int] NOT NULL
,CONSTRAINT [PK_Prodotti] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [Bdx].[Acquisti] (
	[Id] [int] NOT NULL IDENTITY(1,1),
	[IdUtente] [int] NOT NULL,
	[IdProdotto] [int] NOT NULL,
	[Quantita] [int] NOT NULL
,CONSTRAINT [PK_Acquisti] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
,CONSTRAINT [FK_Acquisti_IdUtente] FOREIGN KEY ([IdUtente]) REFERENCES [Bdx].[Utenti] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION
,CONSTRAINT [FK_Acquisti_IdProdotto] FOREIGN KEY ([IdProdotto]) REFERENCES [Bdx].[Prodotti] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION
) ON [PRIMARY]
GO
